---
title: "Clustering - Data Mining Advance"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

 

```{r}
help(kmeans)
set.seed(1)
x=matrix(rnorm(50*2), ncol=2)
plot(x)
x[1:25,1]=x[1:25,1]+3
x[1:25,2]=x[1:25,2]-4
plot(x)
```

```{r}
km.out=kmeans(x,2,nstart=20)
km.out
km.out$cluster
```
```{r}
plot(x, col=(km.out$cluster +1), main="K-Means Clustering Results with K=2", xlab="", ylab="", pch=20, cex=2)
points(km.out$centers,pch=8,cex=2)


```
```{r}
set.seed (2)
km.out=kmeans(x,3,nstart=20)
km.out
```
```{r}
set.seed (3)
km.out=kmeans(x,3,nstart=1)
km.out$tot.withinss
km.out=kmeans(x,3,nstart=20)
km.out$tot.withinss

```
```{r}
iris2 = iris
iris2$Species = NULL
kmeans.result = kmeans(iris2,3,nstart=20)
kmeans.result
table(iris$Species, kmeans.result$cluster)

```
```{r}
plot(iris2[c("Sepal.Length", "Sepal.Width")], col = kmeans.result$cluster)
points(kmeans.result$centers[,c("Sepal.Length", "Sepal.Width")], col = 1:3,pch = 8, cex=2)
```

```{r}
library(cluster)
help(pam)
 pam.result = pam(iris2,3)
 pam.result
 table(pam.result$clustering,iris$Species)
 plot(pam.result)

```
```{r}
 library(RWeka)
 help(SimpleKMeans)

```

